### PR TITLE
fix: convert unix date to RFC3339

### PR DESCRIPTION
**Pull request by cmotelet**
To comply with the Signal K specification, the date must be sent in RFC3339 format.

### CODE REVIEW

**Comment by inspired-technologies** [comment]
Many thanks for raising the PR - this should be fixed with the refactored conversion module.

**Comment by tkrofta** [comment]
Included into refactoring the conversions.

**Review by tkrofta — CHANGES_REQUESTED** [review]
Suggest to close and re-open / new PR if not working as expected within the conversion module.

**Comment by cmotelet** [comment]
It's perfect for me.
This will be fully compliant with the next release of InstrumentPanel:
image

**Pull request closed without merging**
